[package]
name = "actix-websocket-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1"
actix-web = "4"
actix = "0.13"
actix-web-actors = "4.1"
async-stream = "0.3"
